import { useEffect, useMemo, useState } from 'react';
import StatCard from '../../components/StatCard';
import StatusBadge from '../../components/StatusBadge';
import Modal from '../../components/Modal';
import Icon from '../../components/Icon';
import { assignBed, getResidentsForAssignment, getRooms, getSummary, vacateBed } from '../../services/management';

const typeLabels = { SINGLE: '1-Sharing', DOUBLE: '2-Sharing', TRIPLE: '3-Sharing', QUAD: '4-Sharing' };

const RoomsBedMatrix = () => {
  const [rooms, setRooms] = useState([]); const [summary, setSummary] = useState(null); const [residents, setResidents] = useState([]);
  const [activeFloor, setActiveFloor] = useState('all'); const [selectedRoom, setSelectedRoom] = useState(null); const [assigningBed, setAssigningBed] = useState(null);
  const refresh = async () => { const [roomData, summaryData, residentData] = await Promise.all([getRooms(), getSummary(), getResidentsForAssignment()]); setRooms(roomData); setSummary(summaryData); setResidents(residentData); };
  useEffect(() => { refresh().catch(() => {}); }, []);
  const floors = useMemo(() => [...new Set(rooms.map((room) => room.floor))].sort((a, b) => a - b), [rooms]);
  const visibleRooms = activeFloor === 'all' ? rooms : rooms.filter((room) => String(room.floor) === activeFloor);
  const availableResidents = residents.filter((resident) => !resident.bedId);
  const assign = async (bedId, residentId) => { await assignBed(bedId, residentId); setAssigningBed(null); await refresh(); };
  const vacate = async (bedId) => { await vacateBed(bedId); setSelectedRoom(null); await refresh(); };

  return <div className="flex flex-col w-full space-y-space-lg">
    <div className="page-header"><div><span className="px-2 py-0.5 rounded bg-primary-fixed text-on-primary-fixed text-label-sm font-semibold uppercase tracking-wider">Real-Time Inventory</span><h1 className="mt-2 font-headline font-bold text-headline-xl text-on-surface">Rooms & Bed Occupancy Matrix</h1><p className="text-body-md text-on-surface-variant">Live room assignments and bed status from MongoDB.</p></div></div>
    <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-space-md"><StatCard title="Total Beds" value={summary?.occupancy?.totalBeds ?? 0} icon="hotel" iconBg="bg-surface-container" iconColor="text-primary" subtitle="Across all rooms" /><StatCard title="Occupied" value={summary?.occupancy?.occupiedBeds ?? 0} icon="how_to_reg" iconBg="bg-primary-fixed" iconColor="text-on-primary-fixed-variant" /><StatCard title="Available" value={summary?.occupancy?.availableBeds ?? 0} icon="meeting_room" iconBg="bg-surface-container" iconColor="text-secondary" subtitle="Instant check-in ready" /><StatCard title="Notice Period" value={summary?.occupancy?.underNoticeBeds ?? 0} icon="schedule" iconBg="bg-secondary-fixed" iconColor="text-on-secondary-fixed" subtitle="Current bed status" /></div>
    <div className="section-card"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-space-sm pb-space-md border-b border-surface-container"><div><h2 className="font-headline font-semibold text-headline-md text-on-surface flex items-center gap-2"><Icon name="grid_4x4" size={22} className="text-primary" />Bed Assignment Grid</h2><p className="text-body-sm text-on-surface-variant">Click any room card for details.</p></div><div className="inline-flex p-1 bg-surface-container-low rounded-lg gap-1"><button onClick={() => setActiveFloor('all')} className={`px-3 py-1 rounded text-label-sm font-medium ${activeFloor === 'all' ? 'bg-surface-container-lowest text-primary shadow-sm' : 'text-on-surface-variant'}`}>All</button>{floors.map((floor) => <button key={floor} onClick={() => setActiveFloor(String(floor))} className={`px-3 py-1 rounded text-label-sm font-medium ${activeFloor === String(floor) ? 'bg-surface-container-lowest text-primary shadow-sm' : 'text-on-surface-variant'}`}>Floor {floor}</button>)}</div></div>
      <div className="space-y-space-lg pt-2">{floors.filter((floor) => activeFloor === 'all' || String(floor) === activeFloor).map((floor) => { const floorRooms = visibleRooms.filter((room) => room.floor === floor); return <div key={floor}><div className="flex items-center justify-between pb-2"><span className="text-label-md font-bold uppercase tracking-wider text-on-surface">Floor {floor}</span><span className="text-numeric text-on-surface-variant">{floorRooms.flatMap((room) => room.beds).filter((bed) => bed.status === 'OCCUPIED').length}/{floorRooms.flatMap((room) => room.beds).length} Beds Occupied</span></div><div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-space-sm">{floorRooms.map((room) => <div key={room._id} className="p-3 bg-surface-container-low rounded-xl hover:bg-surface-container transition-colors cursor-pointer" onClick={() => setSelectedRoom(room)}><div className="flex items-center justify-between mb-2"><span className="text-label-md font-bold text-on-surface">Room {room.roomNumber}</span><span className="text-label-sm text-outline">{typeLabels[room.type]}</span></div><div className="space-y-1.5">{room.beds.map((bed) => <div key={bed._id} className="flex items-center justify-between text-body-sm p-1.5 rounded-lg bg-surface-container-lowest"><span className="truncate max-w-[180px] text-on-surface font-medium">{bed.label}: {bed.residentId?.userId?.name || bed.status}</span><StatusBadge status={bed.status} /></div>)}</div><div className="mt-2 pt-1.5 border-t border-outline-variant/40 flex justify-between text-label-sm text-outline"><span>₹{room.rent?.toLocaleString('en-IN')}/bed</span><span>{room.beds.filter((bed) => bed.status === 'AVAILABLE').length} Vacant</span></div></div>)}</div></div>; })}</div>
    </div>
    <Modal open={!!selectedRoom} onClose={() => setSelectedRoom(null)} title={`Room ${selectedRoom?.roomNumber || ''} Details`}><div className="space-y-3">{selectedRoom?.beds.map((bed) => <div key={bed._id} className="flex items-center justify-between p-3 rounded-lg bg-surface-container-low"><div><span className="font-semibold">Bed {bed.label}</span><p className="text-body-sm text-on-surface-variant">{bed.residentId?.userId?.name || bed.status}</p></div>{bed.residentId ? <button className="btn-secondary" onClick={() => vacate(bed._id)}>Vacate</button> : bed.status === 'AVAILABLE' ? <select className="input max-w-[180px]" defaultValue="" onChange={(event) => event.target.value && assign(bed._id, event.target.value)}><option value="">Assign resident</option>{availableResidents.map((resident) => <option key={resident._id} value={resident._id}>{resident.userId?.name || resident._id}</option>)}</select> : <StatusBadge status={bed.status} />}</div>)}</div></Modal>
  </div>;
};
export default RoomsBedMatrix;
